# Hungarian translation for apport
# Copyright (c) (c) 2006 Canonical Ltd, and Rosetta Contributors 2006
# This file is distributed under the same license as the apport package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2006.
#
msgid ""
msgstr ""
"Project-Id-Version: apport\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2023-02-23 23:16+0100\n"
"PO-Revision-Date: 2020-04-03 16:38+0000\n"
"Last-Translator: Úr Balázs <balazs@urbalazs.hu>\n"
"Language-Team: Hungarian <hu@li.org>\n"
"Language: hu\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2022-12-07 14:36+0000\n"
"X-Generator: Launchpad (build 41e7553f8097ce3a683f90e835708cbe7bf0006c)\n"

#: ../apport/com.ubuntu.apport.policy.in.h:1
msgid "Collect system information"
msgstr "Rendszer-információk összegyűjtése"

#: ../apport/com.ubuntu.apport.policy.in.h:2
msgid ""
"Authentication is required to collect system information for this problem "
"report"
msgstr ""
"A hibajelentéshez szükséges rendszer-információk összegyűjtéséhez "
"hitelesítés szükséges."

#: ../apport/com.ubuntu.apport.policy.in.h:3
msgid "System problem reports"
msgstr "Rendszerhiba-jelentések"

#: ../apport/com.ubuntu.apport.policy.in.h:4
msgid "Please enter your password to access problem reports of system programs"
msgstr "Adja meg jelszavát a rendszerprogramok hibáinak eléréséhez"

#: ../apport/ui.py:167
msgid "This package does not seem to be installed correctly"
msgstr "Úgy tűnik, ez a csomag nincs megfelelően telepítve"

#: ../apport/ui.py:177
#, python-format
msgid ""
"This does not seem to be an official %s package. Please retry after updating "
"the indexes of available packages, if that does not work then remove related "
"third party packages and try again."
msgstr ""

#: ../apport/ui.py:207
#, python-format
msgid ""
"You have some obsolete package versions installed. Please upgrade the "
"following packages and check if the problem still occurs:\n"
"\n"
"%s"
msgstr ""
"Néhány csomagból egy elavult verzió van telepítve. Frissítse az alábbi "
"csomagokat és ellenőrizze, hogy a probléma ezután is fennáll-e: \n"
"\n"
"%s"

#: ../apport/ui.py:370
msgid "unknown program"
msgstr "ismeretlen program"

#: ../apport/ui.py:373
#, python-format
msgid "Sorry, the program \"%s\" closed unexpectedly"
msgstr "Elnézést, a(z) „%s” program váratlanul összeomlott."

#: ../apport/ui.py:376 ../apport/ui.py:1924
#, python-format
msgid "Problem in %s"
msgstr "Probléma a következőben: %s"

#: ../apport/ui.py:381
msgid ""
"Your computer does not have enough free memory to automatically analyze the "
"problem and send a report to the developers."
msgstr ""
"A számítógépe nem rendelkezik elegendő szabad memóriával a probléma "
"automatikus elemzéséhez és a jelentés elküldéséhez a fejlesztőknek."

#: ../apport/ui.py:441 ../apport/ui.py:459 ../apport/ui.py:632
#: ../apport/ui.py:641 ../apport/ui.py:878 ../apport/ui.py:1688
#: ../apport/ui.py:1885 ../apport/ui.py:1890
msgid "Invalid problem report"
msgstr "Érvénytelen hibajelentés"

#: ../apport/ui.py:442
msgid "You are not allowed to access this problem report."
msgstr "A hibajelentés elérése nem engedélyezett"

#: ../apport/ui.py:450
msgid "Error"
msgstr "Hiba"

#: ../apport/ui.py:452
msgid "There is not enough disk space available to process this report."
msgstr "Nincs elegendő lemezterület a hiba feldolgozásához."

#: ../apport/ui.py:490
msgid "No PID specified"
msgstr ""

#: ../apport/ui.py:492
msgid "You need to specify a PID. See --help for more information."
msgstr ""

#: ../apport/ui.py:503 ../apport/ui.py:608
msgid "Invalid PID"
msgstr "Érvénytelen PID"

#: ../apport/ui.py:504
msgid "The specified process ID does not exist."
msgstr "A megadott folyamatazonosító nem létezik."

#: ../apport/ui.py:509
msgid "Not your PID"
msgstr "Nem az Ön folyamatazonosítója"

#: ../apport/ui.py:510
msgid "The specified process ID does not belong to you."
msgstr "A megadott folyamatazonosító nem Önhöz tartozik."

#: ../apport/ui.py:565
msgid "No package specified"
msgstr "Nincs megadva csomag"

#: ../apport/ui.py:567
msgid ""
"You need to specify a package or a PID. See --help for more information."
msgstr ""
"Meg kell adnia egy csomagot vagy PID azonosítót. További információkért "
"tekintse meg a --help kapcsoló kimenetét."

#: ../apport/ui.py:595
msgid "Permission denied"
msgstr "Hozzáférés megtagadva"

#: ../apport/ui.py:597
msgid ""
"The specified process does not belong to you. Please run this program as the "
"process owner or as root."
msgstr ""
"A megadott folyamat nem Önhöz tartozik. Ezt a programot a folyamat "
"tulajdonosaként vagy rendszergazdaként futtassa."

#: ../apport/ui.py:610
msgid "The specified process ID does not belong to a program."
msgstr "A megadott PID nem programhoz tartozik."

#: ../apport/ui.py:634
#, python-format
msgid "Symptom script %s did not determine an affected package"
msgstr "A(z) %s tünetparancsfájl nem határozott meg érintett csomagot"

#: ../apport/ui.py:642
#, python-format
msgid "Package %s does not exist"
msgstr "A(z) %s csomag nem létezik"

#: ../apport/ui.py:671 ../apport/ui.py:883 ../apport/ui.py:916
#: ../apport/ui.py:926
msgid "Cannot create report"
msgstr "Nem készíthető jelentés"

#: ../apport/ui.py:686 ../apport/ui.py:745 ../apport/ui.py:763
msgid "Updating problem report"
msgstr "Hibajelentés frissítése"

#: ../apport/ui.py:688
msgid ""
"You are not the reporter or subscriber of this problem report, or the report "
"is a duplicate or already closed.\n"
"\n"
"Please create a new report using \"apport-bug\"."
msgstr ""
"Ön nem beküldője vagy feliratkozottja a hibajelentésnek, vagy a jelentés egy "
"duplikátum, esetleg már lezárták.\n"
"\n"
"Készítsen új jelentést az „apport-bug” használatával."

#: ../apport/ui.py:700
msgid ""
"You are not the reporter of this problem report. It is much easier to mark a "
"bug as a duplicate of another than to move your comments and attachments to "
"a new bug.\n"
"\n"
"Subsequently, we recommend that you file a new bug report using \"apport-"
"bug\" and make a comment in this bug about the one you file.\n"
"\n"
"Do you really want to proceed?"
msgstr ""
"Nem Ön küldte be a hibajelentést. Sokkal könnyebb megjelölni egy hibát egy "
"másik duplikátumaként, mint átköltöztetni a hozzászólásait és mellékleteit "
"egy új hibához.\n"
"\n"
"Emiatt azt ajánljuk, hogy nyisson egy új hibajelentést az „apport-bug” "
"használatával, és küldjön egy hozzászólást ehhez a hibához az újonnan "
"nyitottról.\n"
"\n"
"Biztosan folytatja?"

#: ../apport/ui.py:746 ../apport/ui.py:764
msgid "No additional information collected."
msgstr "Nem került gyűjtésre további információ."

#: ../apport/ui.py:827
msgid "What kind of problem do you want to report?"
msgstr "Milyen problémát kíván jelenteni?"

#: ../apport/ui.py:848
msgid "Unknown symptom"
msgstr "Ismeretlen tünet"

#: ../apport/ui.py:849
#, python-format
msgid "The symptom \"%s\" is not known."
msgstr "A(z) „%s” tünet ismeretlen."

#: ../apport/ui.py:885
msgid ""
"The window option cannot be used on Wayland.\n"
"\n"
"Please find the window's process ID and then run 'ubuntu-bug <process ID>'.\n"
"\n"
"The process ID can be found by running the System Monitor application. In "
"the Processes tab, scroll until you find the correct application. The "
"process ID is the number listed in the ID column."
msgstr ""

#: ../apport/ui.py:901
msgid ""
"After closing this message please click on an application window to report a "
"problem about it."
msgstr ""
"Ezen üzenet bezárása után kattintson egy alkalmazásablakra az azzal "
"kapcsolatos hiba jelentéséhez."

#: ../apport/ui.py:918 ../apport/ui.py:927
msgid "xprop failed to determine process ID of the window"
msgstr "Az xprop nem tudta meghatározni az ablak folyamatazonosítóját"

#: ../apport/ui.py:942
#, python-format
msgid "%(prog)s <report number>"
msgstr ""

#: ../apport/ui.py:943
msgid "Specify package name."
msgstr "Adja meg a csomagnevet."

#: ../apport/ui.py:950 ../apport/ui.py:1083
msgid "Add an extra tag to the report. Can be specified multiple times."
msgstr "Extra címke hozzáadása a jelentéshez. Többször is megadható."

#: ../apport/ui.py:988
#, python-format
msgid ""
"%(prog)s [options] [symptom|pid|package|program path|.apport/.crash file]"
msgstr ""

#: ../apport/ui.py:999
msgid ""
"Start in bug filing mode. Requires --package and an optional --pid, or just "
"a --pid. If neither is given, display a list of known symptoms. (Implied if "
"a single argument is given.)"
msgstr ""
"Indítás hibabejelentő módban. A --package és egy elhagyható --pid, vagy csak "
"egy --pid kapcsolót igényel. Ha egyik sincs megadva, az ismert tünetek "
"listáját jeleníti meg. (Egy paraméter megadása is ezt jelenti.)"

#: ../apport/ui.py:1008
msgid "Click a window as a target for filing a problem report."
msgstr "Kattintson egy ablakra az azzal kapcsolatos hiba jelentéséhez."

#: ../apport/ui.py:1017
msgid "Start in bug updating mode. Can take an optional --package."
msgstr ""
"Indítás hibafrissítés módban. Opcionálisan használható a --package kapcsoló."

#: ../apport/ui.py:1026
msgid ""
"File a bug report about a symptom. (Implied if symptom name is given as only "
"argument.)"
msgstr ""
"Hiba bejelentése egy tünetről. (Ha az egyetlen paraméter tünetnév, az is ezt "
"jelenti.)"

#: ../apport/ui.py:1035
msgid ""
"Specify package name in --file-bug mode. This is optional if a --pid is "
"specified. (Implied if package name is given as only argument.)"
msgstr ""
"Csomagnév megadása --file-bug módban. Ez elhagyható, ha a --pid meg van "
"adva. (Ha az egyetlen paraméter egy csomagnév, az is ezt jelenti.)"

#: ../apport/ui.py:1046
msgid ""
"Specify a running program in --file-bug mode. If this is specified, the bug "
"report will contain more information.  (Implied if pid is given as only "
"argument.)"
msgstr ""
"Futó program megadása --file-bug módban. Ha ez meg van adva, a hibajelentés "
"több információt fog tartalmazni."

#: ../apport/ui.py:1054
msgid "The provided pid is a hanging application."
msgstr "A megadott PID egy nem válaszoló alkalmazásra mutat."

#: ../apport/ui.py:1062
#, python-format
msgid ""
"Report the crash from given .apport or .crash file instead of the pending "
"ones in %s. (Implied if file is given as only argument.)"
msgstr ""
"Az összeomlás bejelentése adott .apport vagy .crash fájlból, a(z) %s alatt "
"függőben lévők helyet. (Ha az egyetlen paraméter egy fájl, az is ezt "
"jelenti.)"

#: ../apport/ui.py:1072
msgid ""
"In bug filing mode, save the collected information into a file instead of "
"reporting it. This file can then be reported later on from a different "
"machine."
msgstr ""
"Hibajelentő módban az összegyűjtött információk mentése fájlba a bejelentés "
"helyett. Ez a fájl később másik gépről beküldhető."

#: ../apport/ui.py:1091
msgid "Print the Apport version number."
msgstr "Az Apport verziószámának megjelenítése."

#: ../apport/ui.py:1253
msgid ""
"This will launch apport-retrace in a terminal window to examine the crash."
msgstr ""
"Ez meg fogja nyitni az apport-retrace-t egy terminálban, hogy az "
"megvizsgálja az összeomlást."

#: ../apport/ui.py:1257
msgid "Run gdb session"
msgstr "gdb folyamat futtatása"

#: ../apport/ui.py:1258
msgid "Run gdb session without downloading debug symbols"
msgstr "gdb folyamat futtatása a hibakeresési szimbólumok letöltése nélkül"

#. TRANSLATORS: %s contains the crash report file name
#: ../apport/ui.py:1260
#, python-format
msgid "Update %s with fully symbolic stack trace"
msgstr "%s frissítése teljes szimbolikus veremkiíratással"

#: ../apport/ui.py:1322
msgid "Can't remember send report status settings"
msgstr "Nem lehet megjegyezni a jelentés küldése állapot beállításait"

#: ../apport/ui.py:1326
msgid ""
"Saving crash reporting state failed. Can't set auto or never reporting mode."
msgstr ""
"Az összeomlási jelentés állapotának mentése sikertelen. Nem lehet beállítani "
"az automatikus vagy sohasem jelentési módot."

#: ../apport/ui.py:1408 ../apport/ui.py:1421
msgid ""
"This problem report applies to a program which is not installed any more."
msgstr ""
"Ez a problémajelentés egy olyan programra vonatkozik, amely már nincs "
"telepítve."

#: ../apport/ui.py:1445
#, python-format
msgid ""
"The problem happened with the program %s which changed since the crash "
"occurred."
msgstr ""
"A hiba a(z) „%s” programmal lépett fel, amely megváltozott az összeomlás óta."

#: ../apport/ui.py:1506 ../apport/ui.py:1629 ../apport/ui.py:1894
msgid "This problem report is damaged and cannot be processed."
msgstr "A hibajelentés megsérült és nem dolgozható fel."

#: ../apport/ui.py:1515
msgid "This report is about a package that is not installed."
msgstr "Ez a jelentés egy nem telepített csomagról szól."

#: ../apport/ui.py:1523
msgid "An error occurred while attempting to process this problem report:"
msgstr "Hiba történt a következő hibabejelentés feldolgozása közben:"

#: ../apport/ui.py:1540
msgid ""
"You have two versions of this application installed, which one do you want "
"to report a bug against?"
msgstr ""

#: ../apport/ui.py:1545
#, python-format
msgid "%s snap"
msgstr ""

#: ../apport/ui.py:1546
#, python-format
msgid "%s deb package"
msgstr ""

#: ../apport/ui.py:1586
#, python-format
msgid "%s is provided by a snap published by %s. Contact them via %s for help."
msgstr ""

#: ../apport/ui.py:1591
#, python-format
msgid ""
"%s is provided by a snap published by %s. No contact address has been "
"provided; visit the forum at https://forum.snapcraft.io/ for help."
msgstr ""

#: ../apport/ui.py:1690
msgid "Could not determine the package or source package name."
msgstr "A csomag vagy forrás neve nem állapítható meg."

#: ../apport/ui.py:1715
msgid "Unable to start web browser"
msgstr "A webböngésző nem indítható."

#: ../apport/ui.py:1716
#, python-format
msgid "Unable to start web browser to open %s."
msgstr "A(z) „%s” megnyitásához nem lehet elindítani a webböngészőt."

#: ../apport/ui.py:1840
msgid "Network problem"
msgstr "Hálózati probléma"

#: ../apport/ui.py:1844
msgid ""
"Cannot connect to crash database, please check your Internet connection."
msgstr ""
"Nem lehet kapcsolódni az összeomlás-adatbázishoz, ellenőrizze az "
"internetkapcsolatát."

#: ../apport/ui.py:1876
msgid "Memory exhaustion"
msgstr "Elfogyott a memória"

#: ../apport/ui.py:1878
msgid "Your system does not have enough memory to process this crash report."
msgstr ""
"A rendszere nem rendelkezik elegendő memóriával ezen összeomlásjelentés "
"feldolgozásához."

#: ../apport/ui.py:1929
#, python-format
msgid ""
"The problem cannot be reported:\n"
"\n"
"%s"
msgstr ""
"A hiba nem jelenthető:\n"
"\n"
"%s"

#: ../apport/ui.py:1985 ../apport/ui.py:1997
msgid "Problem already known"
msgstr "A probléma már ismert."

#: ../apport/ui.py:1987
msgid ""
"This problem was already reported in the bug report displayed in the web "
"browser. Please check if you can add any further information that might be "
"helpful for the developers."
msgstr ""
"Ez a probléma már ismert, a webböngészőjében megjelent a hozzátartozó "
"hibajelentés. Ellenőrizze, hogy tud-e további információkkal szolgálni, "
"amelyek hasznosak lehetnek a fejlesztők számára."

#: ../apport/ui.py:1999
msgid "This problem was already reported to developers. Thank you!"
msgstr "Ez a probléma már jelentve volt a fejlesztőknek. Köszönjük!"

#: ../bin/apport-cli.py:84
msgid "Press any key to continue..."
msgstr "A folytatáshoz nyomjon le egy billentyűt…"

#: ../bin/apport-cli.py:91
msgid "What would you like to do? Your options are:"
msgstr "Mit szeretne tenni? A lehetőségek:"

#: ../bin/apport-cli.py:104
#, python-format
msgid "Please choose (%s):"
msgstr "Válasszon (%s):"

#: ../bin/apport-cli.py:172
#, python-format
msgid "(%i bytes)"
msgstr "(%i bájt)"

#: ../bin/apport-cli.py:174 ../gtk/apport-gtk.py:169 ../kde/apport-kde.py:405
msgid "(binary data)"
msgstr "(bináris adatok)"

#: ../bin/apport-cli.py:209 ../gtk/apport-gtk.py:208 ../gtk/apport-gtk.ui.h:6
#: ../kde/apport-kde.py:198
msgid "Send problem report to the developers?"
msgstr "Elküldi a hibajelentést a feljesztőknek?"

#: ../bin/apport-cli.py:211
msgid ""
"After the problem report has been sent, please fill out the form in the\n"
"automatically opened web browser."
msgstr ""
"A hibajelentés elküldése után töltse ki a kérdőívet az\n"
"automatikusan megnyíló webböngészőben."

#: ../bin/apport-cli.py:218
#, python-format
msgid "&Send report (%s)"
msgstr "&Hibajelentés küldése (%s)"

#: ../bin/apport-cli.py:223
msgid "&Examine locally"
msgstr "&Vizsgálat helyileg"

#: ../bin/apport-cli.py:227
msgid "&View report"
msgstr "Hi&bajelentés megtekintése"

#: ../bin/apport-cli.py:230
msgid "&Keep report file for sending later or copying to somewhere else"
msgstr "Hibajelentés megtartása &későbbi küldésre, vagy más helyre másolásra"

#: ../bin/apport-cli.py:235
msgid "Cancel and &ignore future crashes of this program version"
msgstr ""
"Mégse, és ezentúl a programverzió összeomlásainak figyelmen &kívül hagyása"

#: ../bin/apport-cli.py:238 ../bin/apport-cli.py:326 ../bin/apport-cli.py:360
#: ../bin/apport-cli.py:383
msgid "&Cancel"
msgstr "Mé&gse"

#: ../bin/apport-cli.py:267
msgid "Problem report file:"
msgstr "Hibajelentésfájl:"

#: ../bin/apport-cli.py:273 ../bin/apport-cli.py:278
msgid "&Confirm"
msgstr "Meg&erősítés"

#: ../bin/apport-cli.py:277
#, python-format
msgid "Error: %s"
msgstr "Hiba: %s"

#: ../bin/apport-cli.py:283 ../kde/apport-kde.py:455
msgid "Collecting problem information"
msgstr "Információgyűjtés a hibáról"

#: ../bin/apport-cli.py:285
msgid ""
"The collected information can be sent to the developers to improve the\n"
"application. This might take a few minutes."
msgstr ""
"Az összegyűjtött információkat elküldheti a fejlesztőknek, hogy "
"javíthassanak\n"
"az alkalmazáson. A küldés eltarthat pár percig."

#: ../bin/apport-cli.py:301 ../gtk/apport-gtk.ui.h:17 ../kde/apport-kde.py:504
msgid "Uploading problem information"
msgstr "A hibával kapcsolatos információk feltöltése"

#: ../bin/apport-cli.py:303
msgid ""
"The collected information is being sent to the bug tracking system.\n"
"This might take a few minutes."
msgstr ""
"Az összegyűjtött információk elküldése a hibakövető rendszernek.\n"
"Ez eltarthat pár percig."

#: ../bin/apport-cli.py:359
msgid "&Done"
msgstr "&Kész"

#: ../bin/apport-cli.py:365
msgid "none"
msgstr "nincs"

#: ../bin/apport-cli.py:367
#, python-format
msgid "Selected: %s. Multiple choices:"
msgstr "Kiválasztva: %s. További lehetőségek:"

#: ../bin/apport-cli.py:384
msgid "Choices:"
msgstr "Lehetőségek:"

#: ../bin/apport-cli.py:398
msgid "Path to file (Enter to cancel):"
msgstr "Fájl helye (kilépés enterrel):"

#: ../bin/apport-cli.py:404
msgid "File does not exist."
msgstr "A fájl nem létezik."

#: ../bin/apport-cli.py:406
msgid "This is a directory."
msgstr "Ez egy könyvtár."

#: ../bin/apport-cli.py:412
msgid "To continue, you must visit the following URL:"
msgstr "A folytatáshoz meg kell nyitnia a következő URL-címet:"

#: ../bin/apport-cli.py:415
msgid ""
"You can launch a browser now, or copy this URL into a browser on another "
"computer."
msgstr ""
"Elindíthatja most a böngészőt, vagy átmásolhatja ezt az URL-címet egy másik "
"számítógépen lévő böngészőbe."

#: ../bin/apport-cli.py:421
msgid "Launch a browser now"
msgstr "Böngésző indítása most"

#: ../bin/apport-cli.py:437
msgid "No pending crash reports. Try --help for more information."
msgstr ""
"Nincs függőben lévő összeomlás-jelentés. \r\n"
"További információkért tekintse meg a --help kapcsoló kimenetét."

#: ../bin/apport-retrace.py:44
msgid "Do not put the new traces into the report, but write them to stdout."
msgstr ""
"Ne tegye be az új nyomkövetéseket a jelentésbe, hanem írja ki a szabványos "
"kimenetre."

#: ../bin/apport-retrace.py:53
msgid ""
"Start an interactive gdb session with the report's core dump (-o ignored; "
"does not rewrite report)"
msgstr ""
"Interaktív gdb munkamenet indítása a jelentés memóriakiíratásával (a -o "
"figyelmen kívül marad, nem írja újra a jelentést)"

#: ../bin/apport-retrace.py:62
msgid ""
"Write modified report to given file instead of changing the original report"
msgstr ""
"Módosított jelentés írása a megadott fájlba az eredeti jelentés módosítása "
"helyett"

#: ../bin/apport-retrace.py:72
msgid "Remove the core dump from the report after stack trace regeneration"
msgstr ""
"A veremkiíratás ismételt előállítása után a memóriakiíratás eltávolítása a "
"jelentésből"

#: ../bin/apport-retrace.py:80
msgid "Override report's CoreFile"
msgstr "A jelentés CoreFile-jának felülbírálása"

#: ../bin/apport-retrace.py:86
msgid "Override report's ExecutablePath"
msgstr "A jelentés ExecutablePath-jának felülbírálása"

#: ../bin/apport-retrace.py:92
msgid "Override report's ProcMaps"
msgstr "A jelentés ProcMaps-jának felülbírálása"

#: ../bin/apport-retrace.py:98
msgid "Rebuild report's Package information"
msgstr "A jelentés csomaginformációinak újjáépítése"

#: ../bin/apport-retrace.py:105
msgid ""
"Build a temporary sandbox and download/install the necessary packages and "
"debug symbols in there; without this option it assumes that the necessary "
"packages and debug symbols are already installed in the system. The argument "
"points to the packaging system configuration base directory; if you specify "
"\"system\", it will use the system configuration files, but will then only "
"be able to retrace crashes that happened on the currently running release."
msgstr ""
"Ideiglenes homokozó létrehozása, majd ebbe a szükséges csomagok, "
"hibakeresési szimbólumok letöltése/telepítése; enélkül feltételezi, hogy a "
"szükséges csomagok és hibakeresési szimbólumok már telepítve lettek. Az "
"argumentum a csomagkezelő rendszer konfigurációs alapkönyvtárára mutat; a "
"„system” esetén a rendszer konfigurációs fájljait használja, de ekkor csak "
"az aktuálisan futó kiadás összeomlásait lesz képes nyomon követni."

#: ../bin/apport-retrace.py:119
msgid ""
"Build another temporary sandbox for installing gdb and its dependencies "
"using the same release as the report rather than whatever version of gdb you "
"have installed."
msgstr ""
"Állítson össze egy másik, a jelentéssel megegyező kiadást használó átmeneti "
"homokozót a gdb és függőségei telepítéséhez az Ön által telepített "
"valamilyen gdb verzió helyett."

#: ../bin/apport-retrace.py:129
msgid "Report download/install progress when installing packages into sandbox"
msgstr ""
"Homokozóba történő telepítéskor a letöltés/telepítési folyamat kijelzése"

#: ../bin/apport-retrace.py:136
msgid "Prepend timestamps to log messages, for batch operation"
msgstr "Helyezzen időbélyegeket a naplóüzenetek elé, a kötegelt működéshez"

#: ../bin/apport-retrace.py:142
msgid ""
"Create and use third-party repositories from origins specified in reports"
msgstr ""
"Külső tárolók létrehozása és használata a jelentésekben megadott forrásokból"

#: ../bin/apport-retrace.py:150
msgid "Cache directory for packages downloaded in the sandbox"
msgstr "Homokozóba letöltött csomagok gyorsítókönyvtára"

#: ../bin/apport-retrace.py:156
msgid ""
"Directory for unpacked packages. Future runs will assume that any already "
"downloaded package is also extracted to this sandbox."
msgstr ""
"Kicsomagolt csomagok könyvtára. A jövőbeli futások feltételezik, hogy a már "
"kicsomagolt csomagok ugyanebbe a homokozóba lesznek kicsomagolva."

#: ../bin/apport-retrace.py:167 ../bin/apport-valgrind.py:97
msgid ""
"Install an extra package into the sandbox (can be specified multiple times)"
msgstr "Extra csomag homokozóba telepítése (többször is megadható)"

#: ../bin/apport-retrace.py:174
msgid ""
"Path to a file with the crash database authentication information. This is "
"used when specifying a crash ID to upload the retraced stack traces (only if "
"neither -g, -o, nor -s are specified)"
msgstr ""
"Az összeomlási adatbázis hitelesítési információit tartalmazó fájl útvonala. "
"Ez összeomlási azonosító megadásakor használatos az ismételten nyomon "
"követett veremkiíratások feltöltésekor (ha a -g, -o és -s egyike sincs "
"megadva)"

#: ../bin/apport-retrace.py:184
msgid ""
"Display retraced stack traces and ask for confirmation before sending them "
"to the crash database."
msgstr ""
"Ismételten nyomon követett veremkiíratások megjelenítése, és megerősítés "
"kérése a beküldés előtt az összeomlási adatbázisba."

#: ../bin/apport-retrace.py:192
msgid "Path to the duplicate sqlite database (default: no duplicate checking)"
msgstr ""
"Útvonal a kettőzött sqlite adatbázishoz (alapértelmezett: nincs ellenőrzés)"

#: ../bin/apport-retrace.py:200
msgid "Do not add StacktraceSource to the report."
msgstr "Ne adja hozzá a veremkövetés forrását a jelentéshez."

#: ../bin/apport-retrace.py:213
msgid "You cannot use -C without -S. Stopping."
msgstr "Nem használhatja a -C kapcsolót az -S kapcsoló nélkül. Leállítás."

#. translators: don't translate y/n,
#. apport currently only checks for "y"
#: ../bin/apport-retrace.py:243
msgid "OK to send these as attachments? [y/n]"
msgstr "Elküldhetők ezek mellékletként? [y/n]"

#: ../bin/apport-unpack.py:29
#, python-format
msgid "%(prog)s <report> <target directory>"
msgstr ""

#: ../bin/apport-unpack.py:31
msgid "Report file to unpack"
msgstr ""

#: ../bin/apport-unpack.py:33
msgid "directory to unpack report to"
msgstr ""

#: ../bin/apport-unpack.py:59
msgid "Destination directory exists and is not empty."
msgstr "A célkönyvtár létezik és nem üres."

#: ../bin/apport-valgrind.py:37
msgid "See man page for details."
msgstr "Részletekért lásd a man oldalt."

#: ../bin/apport-valgrind.py:46
msgid "specify the log file name produced by valgrind"
msgstr "Adja meg a Valgrind naplófájl nevét"

#: ../bin/apport-valgrind.py:52
msgid ""
"reuse a previously created sandbox dir (SDIR) or, if it does not exist, "
"create it"
msgstr ""
"Korábban létrehozott sandbox mappa (SDIR) újra felhasználása, vagy ha nem "
"létezik, létrehozása"

#: ../bin/apport-valgrind.py:60
msgid ""
"do  not  create  or reuse a sandbox directory for additional debug symbols "
"but rely only on installed debug symbols."
msgstr ""
"Ne hozzon létre vagy használjon fel újra homokozó mappát további "
"hibakeresési szimbólumokhoz, csak a telepített hibakeresési szimbólumokat "
"használja."

#: ../bin/apport-valgrind.py:69
msgid ""
"reuse a previously created cache dir (CDIR) or, if it does not exist, create "
"it"
msgstr ""
"Korábban létrehozott gyorsítókönyvtár (CDIR) újra felhasználása, vagy ha nem "
"létezik, létrehozása"

#: ../bin/apport-valgrind.py:78
msgid "report download/install progress when installing packages into sandbox"
msgstr ""
"Letöltési/telepítési folyamat jelentése csomagok telepítésekor a homokozóba"

#: ../bin/apport-valgrind.py:86
msgid ""
"the executable that is run under valgrind's memcheck tool for memory leak "
"detection"
msgstr ""

#: ../bin/apport-valgrind.py:129
#, python-format
msgid "Error: %s is not an executable. Stopping."
msgstr "Hiba: a(z) %s nem végrehajtható. Leállítás."

#: ../data/apportcheckresume.py:67
msgid ""
"This occurred during a previous suspend, and prevented the system from "
"resuming properly."
msgstr ""
"Ez egy korábbi felfüggesztés közben történt, és ezzel megakadályozta a "
"rendszer megfelelő indulását."

#: ../data/apportcheckresume.py:72
msgid ""
"This occurred during a previous hibernation, and prevented the system from "
"resuming properly."
msgstr ""
"Ez egy korábbi hibernálás közben történt, és ezzel megakadályozta a rendszer "
"megfelelő indulását."

#: ../data/apportcheckresume.py:80
msgid ""
"The resume processing hung very near the end and will have appeared to have "
"completed normally."
msgstr ""
"A folytatás feldolgozása a vége felé megszakadt, és úgy fog tűnni, hogy "
"normálisan befejeződött."

#: ../data/kernel_oops.py:30
msgid "Your system might become unstable now and might need to be restarted."
msgstr "A rendszer instabillá válhatott, és szükség lehet az újraindítására."

#: ../gtk/apport-gtk.desktop.in.h:1 ../kde/apport-kde-mime.desktop.in.h:1
#: ../kde/apport-kde.desktop.in.h:1
msgid "Report a problem..."
msgstr "Hiba jelentése…"

#: ../gtk/apport-gtk.desktop.in.h:2 ../kde/apport-kde-mime.desktop.in.h:2
#: ../kde/apport-kde.desktop.in.h:2
msgid "Report a malfunction to the developers"
msgstr "Hibás működés jelentése a fejlesztőknek"

#: ../gtk/apport-gtk.py:185
#, python-format
msgid "Sorry, the application %s has stopped unexpectedly."
msgstr "Elnézést, a(z) %s alkalmazás váratlanul leállt."

#: ../gtk/apport-gtk.py:188
#, python-format
msgid "Sorry, %s has closed unexpectedly."
msgstr "Elnézést, a(z) %s váratlanul befejeződött."

#: ../gtk/apport-gtk.py:193 ../kde/apport-kde.py:213 ../kde/apport-kde.py:265
#, python-format
msgid "Sorry, %s has experienced an internal error."
msgstr "Elnézést, a(z) %s belső hibát észlelt."

#: ../gtk/apport-gtk.py:216 ../gtk/apport-gtk.ui.h:14 ../kde/apport-kde.py:206
msgid "Send"
msgstr "Küldés"

#: ../gtk/apport-gtk.py:234 ../gtk/apport-gtk.py:660 ../gtk/apport-gtk.ui.h:11
#: ../kde/apport-kde.py:329
msgid "Show Details"
msgstr "Részletek megjelenítése"

#: ../gtk/apport-gtk.py:247 ../kde/apport-kde.py:257 ../kde/apport-kde.py:275
msgid "Continue"
msgstr "Folytatás"

#: ../gtk/apport-gtk.py:271
#, python-format
msgid "The application %s has stopped responding."
msgstr "A(z) %s alkalmazás nem válaszol."

#: ../gtk/apport-gtk.py:275
#, python-format
msgid "The program \"%s\" has stopped responding."
msgstr "A(z) „%s” program nem válaszol."

#: ../gtk/apport-gtk.py:292 ../kde/apport-kde.py:221
#, python-format
msgid "Package: %s"
msgstr "Csomag: %s"

#: ../gtk/apport-gtk.py:298 ../kde/apport-kde.py:228
msgid "Sorry, a problem occurred while installing software."
msgstr "Elnézést, hiba történt a szoftvertelepítés alatt."

#: ../gtk/apport-gtk.py:310 ../gtk/apport-gtk.py:334 ../kde/apport-kde.py:237
#, python-format
msgid "The application %s has experienced an internal error."
msgstr "A(z) %s alkalmazás belső hibát észlelt."

#: ../gtk/apport-gtk.py:316 ../kde/apport-kde.py:244
#, python-format
msgid "The application %s has closed unexpectedly."
msgstr "A(z) %s alkalmazás váratlanul befejeződött."

#: ../gtk/apport-gtk.py:347 ../gtk/apport-gtk.ui.h:7 ../kde/apport-kde.py:270
msgid "If you notice further problems, try restarting the computer."
msgstr ""
"Ha további problémákat észlel, próbálja meg újraindítani a számítógépet."

#: ../gtk/apport-gtk.py:352 ../kde/apport-kde.py:277
msgid "Ignore future problems of this type"
msgstr "Ilyen típusú problémák figyelmen kívül hagyása a jövőben"

#: ../gtk/apport-gtk.py:664 ../kde/apport-kde.py:326
msgid "Hide Details"
msgstr "Részletek elrejtése"

#: ../gtk/apport-gtk.ui.h:1 ../kde/apport-kde.py:545 ../kde/apport-kde.py:588
msgid "Apport"
msgstr "Apport"

#: ../gtk/apport-gtk.ui.h:2
msgid "Cancel"
msgstr "Mégse"

#: ../gtk/apport-gtk.ui.h:3
msgid "OK"
msgstr "Ok"

#: ../gtk/apport-gtk.ui.h:4
msgid "Crash report"
msgstr "Összeomlás-jelentés"

#: ../gtk/apport-gtk.ui.h:5
msgid "<big><b>Sorry, an internal error happened.</b></big>"
msgstr "<big><b>Elnézést, belső hiba történt.</b></big>"

#: ../gtk/apport-gtk.ui.h:8
msgid "Remember this in future"
msgstr "Emlékezzen erre a jövőben"

#: ../gtk/apport-gtk.ui.h:9
msgid "Ignore future problems of this program version"
msgstr "Ezen programverzió további problémáinak figyelmen kívül hagyása"

#: ../gtk/apport-gtk.ui.h:10
msgid "Relaunch this application"
msgstr "Az alkalmazás újraindítása"

#: ../gtk/apport-gtk.ui.h:12
msgid "_Examine locally"
msgstr "_Vizsgálat helyileg"

#: ../gtk/apport-gtk.ui.h:13
msgid "Don't send"
msgstr "Ne küldje el"

#: ../gtk/apport-gtk.ui.h:15
msgid "<big><b>Collecting problem information</b></big>"
msgstr "<big><b>Információgyűjtés a problémáról</b></big>"

#: ../gtk/apport-gtk.ui.h:16
msgid ""
"Information is being collected that may help the developers fix the problem "
"you report."
msgstr ""
"Információk gyűjtése, amelyek segíthetik a fejlesztőket a jelentendő "
"probléma megoldásában."

#: ../gtk/apport-gtk.ui.h:18
msgid "<big><b>Uploading problem information</b></big>"
msgstr "<big><b>Hibainformációk feltöltése</b></big>"

#: ../gtk/apport-gtk.ui.h:19 ../kde/apport-kde.py:506
msgid ""
"The collected information is being sent to the bug tracking system. This "
"might take a few minutes."
msgstr ""
"Az összegyűjtött információk elküldésre kerülnek a hibakövető rendszerbe. Ez "
"eltarthat néhány percig."

#: ../kde/apport-kde-mimelnk.desktop.in.h:1
msgid "Apport crash file"
msgstr "Apport jelentésfájl"

#: ../kde/apport-kde.py:260
msgid "Leave Closed"
msgstr "Bezárva hagyás"

#: ../kde/apport-kde.py:261 ../kde/apport-kde.py:425
msgid "Relaunch"
msgstr "Újraindítás"

#: ../kde/apport-kde.py:354
msgid "Username:"
msgstr "Felhasználónév:"

#: ../kde/apport-kde.py:355
msgid "Password:"
msgstr "Jelszó:"

#: ../kde/apport-kde.py:454
msgid "Collecting Problem Information"
msgstr "Információgyűjtés a hibáról"

#: ../kde/apport-kde.py:457
msgid ""
"The collected information can be sent to the developers to improve the "
"application. This might take a few minutes."
msgstr ""
"Az összegyűjtött információk elküldhetők a fejlesztőknek az alkalmazás "
"javítása érdekében. Ez eltarthat néhány percig."

#: ../kde/apport-kde.py:503
msgid "Uploading Problem Information"
msgstr "A hibával kapcsolatos információk feltöltése"
